### ISSUE TITLE
Code Availability

### ISSUE THREAD

**Issue by oldmonkABA** [coveooss/ecommerce-query-embeddings#1]
Hi 

When will the code be available?

**Comment by jacopotagliabue** [comment]
Hi, thanks for reaching out! We had some team re-org after the publication, and then busy with other OS activities (e.g. SIGIR data challenge: https://github.com/coveooss/SIGIR-ecom-data-challenge)! 

But we definitely did not forget - we hope to release our code soon: stay tuned with this and all our other initiatives.
